version: '3.8'

services:
  consumer:
    build:
      context: ../.
      dockerfile: ./images/consumer
    environment:
      IP: ${IP}
      IP_CLIENT: ${IP_CLIENT}
    deploy:
      mode: replicated
      replicas: 3