name: CI/CD Check

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Check for CI/CD files
      id: checkfiles
      run: |
        echo "Checking for CI/CD configuration files..."
        if [ -f ".circleci/config.yml" ] || [ -f ".gitlab-ci.yml" ] || [ -f ".travis.yml" ] || [ -f "azure-pipelines.yml" ] || [ -f "Jenkinsfile" ] || [ -f ".ci/config" ] || [ -f ".ci-config" ]; then
          echo "::set-output name=found::true"
        else
          echo "::set-output name=found::false"
        fi

    # Use the output from the `checkfiles` step
    - name: Output result
      run: |
        if [ "${{ steps.checkfiles.outputs.found }}" == "true" ]; then
          echo "CI/CD configurations found."
        else
          echo "No CI/CD configurations found."
        fi
